### ISSUE TITLE
change your repository name 

### ISSUE THREAD

**Issue by kamontat** [JirayuL/GuessingGame#1]
see more at [link](https://bitbucket.org/skeoop/oop/src/aec82183ce9769176efdbddfa7c11446235477b6/week1/Lab1-3-Guessing-Game.pdf?at=master)

**Comment by JirayuL** [comment]
I change repos from week1 to oopII.

**Comment by kamontat** [comment]
please read the slide clearly. otherwise you may not get any score

**Comment by JirayuL** [comment]
My bad. I am so sorry about that. I change from oopII to GuessingGame.
